### ISSUE TITLE
After bootstrapping a new replica for a library with 10k+ baselines, metadata is intact but no collection docs are written

### ISSUE THREAD

**Issue by a-type** [a-type/verdant#353]
Nothing obviously bad in logs, besides there simply being a ton of reactive updates as everything gets loaded in.

I think it's time to re-approach the `reset` sync handling to bypass reactivity and re-initialize the client.

**Comment by a-type** [comment]
Oh, this was in there...

```
error Error saving entities to queryable storage DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at createAbortableTransaction (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:930:17)
    at IDBService.createTransaction (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:974:18)
    at QueryableStorage.saveEntities (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:4073:27)
    at EntityStore.processData (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:4231:37)
    at async EntityStore.addData (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:4162:7)
    at async ServerSync.handleMessage (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:5222:11)
```

**Comment by a-type** [comment]
Looks like it's due to old collection data being present in the sync.

Short term solution: filter out old data before saving document indexes.

Longer term: need to clean out old collections so there aren't dead docs in sync data forever.

**Comment by a-type** [comment]
First mitigation implemented. Tested and works.

Second part is covered in #313

**Comment by xmsz-stu** [comment]
> Oh, this was in there...Oh, this was in there... 哦，这是在那儿......
> 
> ```
> error Error saving entities to queryable storage DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
>     at createAbortableTransaction (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:930:17)
>     at IDBService.createTransaction (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:974:18)
>     at QueryableStorage.saveEntities (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:4073:27)
>     at EntityStore.processData (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:4231:37)
>     at async EntityStore.addData (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:4162:7)
>     at async ServerSync.handleMessage (http://localhost:4444/node_modules/.vite/deps/chunk-X6WNNQHJ.js?v=a178b073:5222:11)
> ```

I am also encountering this error. How can I resolve it? 
When testing locally, I can delete all IndexedDB data and start over, 
but on other devices, I cannot perform these operations. Now, it keeps showing this result. How can I clear it?

**Comment by a-type** [comment]
@xmsz-stu This would indicate that documents are being synced to a device which belong to collections that have since been deleted by a schema migration.

Are you sure it's the same error? The error message suggests you're on an older version of Verdant Store (pre-v4.0) since the QueryableStorage class was replaced with the new Persistence abstractions. Before 4.0, I attempted to patch this bug before closing this issue in this commit, nearly a year ago: https://github.com/a-type/verdant/commit/064a09449ac27115f2dc47a358d38b8a9e53c468

If you have a repository which reproduces the bug, please link to it if upgrading to 4.0 doesn't work. Upgrading should not require any manual changes, but you will have to upgrade to the latest CLI version and regenerate your client from the existing schema.
