### ISSUE TITLE
[HELP]Can't install @verdant-web/server

### ISSUE THREAD

**Issue by xmsz-stu** [a-type/verdant#444]
Your project is truly excellent! My environment is specified as nodejs 22.x/nodejs 23.x. However, I am unable to install @verdant-web/server as the build of better-sqlite3 has failed. It is possible that the version of better-sqlite3 is overly outdated. Thus, which version of nodejs can I install?

**Comment by a-type** [comment]
Thanks for trying it. I've still been on 18 or 20 myself, but I'll look into upgrading the sqlite dependency. I've been meaning to move to a more recent Node version.

**Comment by a-type** [comment]
I have updated the better-sqlite3 dependency in prerelease version `@verdant-web/server@3.3.4-alpha.2`. This version should be compatible with the current official releases of other packages. I'll test it with my own projects soon, but in the meantime if you have a chance, give it a shot.

**Comment by xmsz-stu** [comment]
Thanks!  I will try nodejs 20.x！

**Comment by a-type** [comment]
I've released a stable version of the server which should now work with Node 20/22 and tested it by upgrading https://github.com/a-type/biscuits . All seems to work well.
